=== fmadler/minuteproject/minuteproject-code/mvn/kernel/src/main/config/catalog/mp-template-config.xsd
<xs:schema id="target" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns="http://minuteproject.sf.net/xsd/mp-template-config"
	targetNamespace="http://minuteproject.sf.net/xsd/mp-template-config"
	elementFormDefault="qualified">

	<xs:element name="target" type="target">
	</xs:element>

	<xs:complexType name="target">
		<xs:sequence>
			<xs:element name="architecture-target" type="architecture-target"
				minOccurs="0" maxOccurs="unbounded">
			</xs:element>
			<xs:element name="plugin" type="plugin" minOccurs="0"
				maxOccurs="unbounded">
			</xs:element>
			<xs:element name="template-target" type="template-target"
				minOccurs="0" maxOccurs="unbounded">
			</xs:element>
			<xs:element name="resource-target" type="resource-target"
				minOccurs="0" maxOccurs="unbounded">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="architecture-target">
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="description" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="plugin">
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="className" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="property">
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="value" type="xs:string" />
		<xs:attribute name="tag" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="template">
		<xs:sequence>
			<xs:element name="property" type="property" minOccurs="0"
				maxOccurs="unbounded">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="templateFileName" type="xs:string" />
		<xs:attribute name="subdir" type="xs:string" />
		<xs:attribute name="outputsubdir" type="xs:string" />
		<xs:attribute name="technicalPackage" type="xs:string" />
		<xs:attribute name="add-model-name" type="xs:boolean" />
		<xs:attribute name="add-model-dir-name" type="xs:boolean" />
		<xs:attribute name="add-package-name" type="xs:boolean" />
		<xs:attribute name="add-business-package-dir-name" type="xs:boolean" />
		<xs:attribute name="file-extension" type="xs:string" />
		<xs:attribute name="scope-specific-value" type="xs:string" />
		<xs:attribute name="has-updatable-nature" type="xs:boolean" />
		<xs:attribute name="file-prefix" type="xs:string" />
		<xs:attribute name="file-suffix" type="xs:string" />
		<xs:attribute name="entity-specific" type="xs:string" />
		<xs:attribute name="package-specific" type="xs:string" />
		<xs:attribute name="model-specific" type="xs:string" />
		<xs:attribute name="check-template-to-generate" type="xs:string" />
		<xs:attribute name="is-template-to-generate-method" type="xs:string" />
		<xs:attribute name="field-specific" type="xs:string" />
		<xs:attribute name="file-name-builder-plugin" type="xs:string" />
		<xs:attribute name="file-name-builder-method" type="xs:string" />
		<xs:attribute name="application-specific" type="xs:string" />
		<xs:attribute name="package-root" type="xs:string" />
		<xs:attribute name="add-technical-dir-name" type="xs:boolean" />
	</xs:complexType>

	<xs:complexType name="template-target">
		<xs:sequence>
			<xs:element name="template" type="template" minOccurs="0"
				maxOccurs="unbounded">
			</xs:element>
			<xs:element name="property" type="property" minOccurs="0"
				maxOccurs="unbounded">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="libdir" type="xs:string" />
		<xs:attribute name="tool" type="xs:string" />
		<xs:attribute name="outputdir" type="xs:string" />
		<xs:attribute name="package-root" type="xs:string" />
		<xs:attribute name="belongToPackage" type="xs:string" />
		<xs:attribute name="templatedir" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="resource-target">
		<xs:sequence>
			<xs:element name="resource" type="resource" minOccurs="0"
				maxOccurs="unbounded">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="outputdir" type="xs:string" />
	</xs:complexType>
	
	<xs:complexType name="resource">
		<xs:sequence>
			<xs:element name="property" type="property" minOccurs="0"
				maxOccurs="unbounded">
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" />
		<xs:attribute name="resource-file-name" type="xs:string" />
	</xs:complexType>

</xs:schema>

=== fmadler/minuteproject/minuteproject-code/mvn/kernel/src/main/config/catalog/mp-template-config-SpringData.xml
<target name="Spring service"
xmlns="http://minuteproject.sf.net/xsd/mp-template-config" 
xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
xs:schemaLocation="./mp-template-config.xsd">
	<architecture-target name="Spring service" description="Spring service architecture">
	</architecture-target>	

	<template-target 
    	name="Spring data"
		libdir="lib/SPRING_LIB.vm"
		outputdir="src/main/java"
		belongToPackage="true">
		<property name="DomainEntityUMLTemplate" value="DomainEntityJPA2Annotation" />

		<template name="SpringDataModelRepository" templateFileName="SpringDataModelRepository.vm" 
			outputsubdir="" technicalPackage="repository"
			file-extension="java" file-prefix="" file-suffix="Repository" 
			model-specific="true"
			has-updatable-nature="true">
		</template>	

		<template name="SpringDataEntityRepository" templateFileName="SpringDataEntityRepository.vm" 
			outputsubdir="" technicalPackage="repository"
			file-extension="java" file-prefix="" file-suffix="Repository" 
			entity-specific="true"
			check-template-to-generate="true" is-template-to-generate-method="enrichmentUtils.isToGenerateBasedOnNotMany2Many"
			has-updatable-nature="true">
		</template>	

	</template-target>

    <template-target 
        name="Spring data"
        libdir="lib/SPRING_LIB.vm"
        outputdir=""
        package-root="">

        <template name="PomXml.springdata" templateFileName="PomXml.springdata.vm" 
            subdir="" outputsubdir="" technicalPackage="" has-updatable-nature="true"
            file-extension="xml" file-prefix="pom" file-suffix="" 
            application-specific="true" add-model-name="false">
        </template> 
                    
    </template-target>      
                    
</target>

=== fmadler/minuteproject/minuteproject-code/mvn/kernel/src/main/config/catalog/mp-template-config-springboot@eucomm.xml
<target name="springboot"
xmlns="http://minuteproject.sf.net/xsd/mp-template-config" 
xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
xs:schemaLocation="./mp-template-config.xsd">	
	<architecture-target name="springboot eucomm security"/>

	<template-target
			name="Spring boot eulogin integration"
			outputdir="src/main/java"
			belongToPackage="true">

		<template name="SpringBoot.eulogin.J2eePreAuthenticatedProcessingFilter" templateFileName="SpringBoot.eulogin.J2eePreAuthenticatedProcessingFilter.vm"
				  subdir="" outputsubdir="" technicalPackage="security.eulogin.spring"
				  file-extension="java" file-prefix="" file-suffix="J2eePreAuthenticatedProcessingFilter"
				  scope-specific-value="model" add-model-name="false">
			<!-- TODO scope-specific-value="application" with correct packagename "application-package"-->
		</template>

		<template name="SpringBoot.eulogin.SecurityConfiguration" templateFileName="SpringBoot.eulogin.SecurityConfiguration.vm"
				  subdir="" outputsubdir="" technicalPackage="security.eulogin.spring"
				  file-extension="java" file-prefix="" file-suffix="SecurityConfiguration"
				  scope-specific-value="model" add-model-name="false">
			<!-- TODO scope-specific-value="application" with correct packagename "application-package"-->
		</template>

		<template name="SpringBoot.eulogin.UserDetailsServiceWrapper" templateFileName="SpringBoot.eulogin.UserDetailsServiceWrapper.vm"
				  subdir="" outputsubdir="" technicalPackage="security.eulogin.spring"
				  file-extension="java" file-prefix="" file-suffix="UserDetailsServiceWrapper"
				  scope-specific-value="model" add-model-name="false">
		</template>

		<template name="SpringBoot.eulogin.WebMvcConfiguration" templateFileName="SpringBoot.eulogin.WebMvcConfiguration.vm"
				  subdir="" outputsubdir="" technicalPackage="security.eulogin.spring"
				  file-extension="java" file-prefix="" file-suffix="WebMvcConfiguration"
				  scope-specific-value="model" add-model-name="false">
		</template>

		<!-- tomcat -->
		<template name="SpringBoot.tomcat.SecurityWithEcasAuthenticator" templateFileName="SpringBoot.tomcat.SecurityWithEcasAuthenticator.vm"
				  subdir="" outputsubdir="" technicalPackage="security.eulogin.tomcat"
				  file-extension="java" file-prefix="" file-suffix="TomcatSecurityWithEcasAuthenticator"
				  scope-specific-value="model" add-model-name="false">
		</template>

		<!-- user role temp to use master-data with enum for global role -->
		<template name="SpringBoot.global.Role" templateFileName="SpringBoot.global.Role.vm"
				  subdir="" outputsubdir="" technicalPackage="security.eulogin.role"
				  file-extension="java" file-prefix="" file-suffix="Role"
				  scope-specific-value="model" add-model-name="false">
		</template>

		<!-- eulogin -->
		<template name="Eulogin.UserDetailsExtraGroupHandler" templateFileName="Eulogin.UserDetailsExtraGroupHandler.vm"
				  subdir="" outputsubdir="" technicalPackage="security.eulogin"
				  file-extension="java" file-prefix="" file-suffix="UserDetailsExtraGroupHandler"
				  scope-specific-value="model" add-model-name="false">
		</template>

		<template name="SpringBoot.eulogin.GrantedAuthority" templateFileName="SpringBoot.eulogin.GrantedAuthority.vm"
				  subdir="" outputsubdir="" technicalPackage="security.eulogin"
				  file-extension="java" file-prefix="" file-suffix="EuLoginGrantedAuthority"
				  scope-specific-value="model" add-model-name="false">
		</template>

		<template name="SpringBoot.eulogin.UserDetails" templateFileName="SpringBoot.eulogin.UserDetails.vm"
				  subdir="" outputsubdir="" technicalPackage="security.eulogin"
				  file-extension="java" file-prefix="" file-suffix="EuLoginUserDetails"
				  scope-specific-value="model" add-model-name="false">
		</template>

	</template-target>

	<template-target
			name="Spring boot eulogin integration"
			outputdir="src/main/resources"
			belongToPackage="true">

		<template name="EuLogin.ecas-config.properties" templateFileName="EuLogin.ecas-config.properties.vm"
				  package-root="" add-model-dir-name="false" add-business-package-dir-name="false" add-technical-dir-name="false"
				  file-extension="properties" file-suffix="ecas-config"
				  add-package-name="false"
				  scope-specific-value="model" add-model-name="false">
		</template>

	</template-target>

</target>

=== fmadler/minuteproject/minuteproject-code/mvn/kernel/src/main/config/catalog/mp-template-config-cas-security.xml
<target name="springboot"
xmlns="http://minuteproject.sf.net/xsd/mp-template-config" 
xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
xs:schemaLocation="./mp-template-config.xsd">	
	<architecture-target name="cas security authentication" description="CAS Security Authentication"/>

	<template-target
			name="CAS resources"
			outputdir="src/main/resources"
			belongToPackage="true">

		<template name="Cas.ecas-config.xml" templateFileName="Cas.ecas-config.xml.vm"
				  subdir="" outputsubdir="" technicalPackage=""
				  file-extension="xml" file-prefix="" file-suffix="ecas-config"
				  scope-specific-value="application" add-model-name="false" add-package-name="false"
				  check-template-to-generate="true" is-template-to-generate-method="enrichmentUtils.isToGenerateBasedOnPropertyPresenceValue"
		>
			<property name="property-presence" value="securityAuthenticationType"></property>
			<property name="property-presence-value" value="cas"></property>
		</template>

	</template-target>

	<template-target
			name="CAS server config"
			outputdir="src/main/webapp/WEB-INF"
			belongToPackage="true">

		<template name="Cas.WebXml" templateFileName="Cas.WebXml.vm"
				  subdir="" outputsubdir="" technicalPackage=""
				  file-extension="xml" file-prefix="" file-suffix="web"
				  scope-specific-value="application" add-model-name="false" add-package-name="false"
				  check-template-to-generate="true" is-template-to-generate-method="enrichmentUtils.isToGenerateBasedOnPropertyPresenceValue"
		>
			<property name="property-presence" value="securityAuthenticationType"></property>
			<property name="property-presence-value" value="cas"></property>
		</template>

		<template name="Cas.WeblogicXml" templateFileName="Cas.WeblogicXml.vm"
				  subdir="" outputsubdir="" technicalPackage=""
				  file-extension="xml" file-prefix="" file-suffix="weblogic"
				  scope-specific-value="application" add-model-name="false" add-package-name="false"
				  check-template-to-generate="true" is-template-to-generate-method="enrichmentUtils.isToGenerateBasedOnPropertyPresenceValue"
		>
			<property name="property-presence" value="securityAuthenticationType"></property>
			<property name="property-presence-value" value="cas"></property>
		</template>

	</template-target>

</target>
